from app.models.auth import (
    APIKey,
    APIKeyScope,
    Locale,
    LoginAuditLog,
    MFARecoveryCode,
    MFAMethod,
    OTPChallenge,
    PasswordHistory,
    PasswordResetToken,
    Permission,
    RefreshToken,
    Role,
    RolePermission,
    Session,
    User,
)
from app.models.base import Base
from app.models.education import AuditLog, File, Guardian, Student, Subject, SystemSetting, TrainingCenter, Translation
from app.models.location import Mahalla, Region

__all__ = [
    "APIKey",
    "APIKeyScope",
    "AuditLog",
    "Base",
    "File",
    "Guardian",
    "Locale",
    "LoginAuditLog",
    "MFARecoveryCode",
    "MFAMethod",
    "Mahalla",
    "OTPChallenge",
    "PasswordHistory",
    "PasswordResetToken",
    "Permission",
    "RefreshToken",
    "Region",
    "Role",
    "RolePermission",
    "Session",
    "Student",
    "Subject",
    "SystemSetting",
    "TrainingCenter",
    "Translation",
    "User",
]
