"""Role-based permissions for TMB platform operations."""

MANDATORY_MFA_ROLES = {"super_admin", "hokimiyat_operator", "center_director"}

ROLE_PERMISSIONS: dict[str, list[str]] = {
    "super_admin": [
        "centers.create",
        "centers.read",
        "centers.update",
        "centers.delete",
        "students.create",
        "students.read",
        "students.update",
        "students.delete",
        "teachers.create",
        "teachers.read",
        "teachers.update",
        "teachers.delete",
        "groups.create",
        "groups.read",
        "groups.update",
        "groups.delete",
        "groups.enroll",
        "attendance.read",
        "attendance.mark",
        "payments.read",
        "payments.create",
        "payments.update",
        "ratings.view",
        "reports.generate",
        "system.settings",
        "users.password_reset",
        "audit.read",
        "dashboard.view",
        "analytics.view",
    ],
    "hokimiyat_operator": [
        "centers.read",
        "students.read",
        "teachers.read",
        "groups.read",
        "attendance.read",
        "payments.read",
        "ratings.view",
        "reports.generate",
        "audit.read",
        "dashboard.view",
        "analytics.view",
    ],
    "center_director": [
        "centers.read",
        "centers.update",
        "students.create",
        "students.read",
        "students.update",
        "students.delete",
        "teachers.create",
        "teachers.read",
        "teachers.update",
        "groups.create",
        "groups.read",
        "groups.update",
        "groups.delete",
        "groups.enroll",
        "attendance.read",
        "attendance.mark",
        "payments.read",
        "payments.create",
        "payments.update",
        "ratings.view",
        "reports.generate",
        "users.password_reset",
        "dashboard.view",
        "analytics.view",
    ],
    "center_admin": [
        "centers.read",
        "students.create",
        "students.read",
        "students.update",
        "teachers.read",
        "groups.create",
        "groups.read",
        "groups.update",
        "groups.enroll",
        "attendance.read",
        "attendance.mark",
        "payments.read",
        "payments.create",
        "ratings.view",
        "dashboard.view",
    ],
    "teacher": [
        "students.create",
        "students.read",
        "students.update",
        "groups.read",
        "attendance.read",
        "attendance.mark",
        "ratings.view",
        "dashboard.view",
    ],
    "auditor": [
        "centers.read",
        "students.read",
        "teachers.read",
        "groups.read",
        "attendance.read",
        "payments.read",
        "ratings.view",
        "reports.generate",
        "audit.read",
        "pinfl.reveal",
        "dashboard.view",
        "analytics.view",
    ],
    "parent": [
        "students.read",
        "ratings.view",
        "certificates.read",
    ],
    "external_api": [
        "aggregate_stats.read",
    ],
}

ROLE_DEFINITIONS = [
    ("super_admin", "Super administrator", "Super administrator", "Super administrator"),
    ("hokimiyat_operator", "Hokimiyat operatori", "Оператор хокимията", "Hokimiyat operator"),
    ("center_director", "Markaz direktori", "Директор центра", "Center director"),
    ("center_admin", "Markaz administratori", "Администратор центра", "Center admin / Menejer"),
    ("teacher", "O'qituvchi", "Учитель", "Teacher"),
    ("auditor", "Auditor", "Аудитор", "Auditor"),
    ("parent", "Ota-ona", "Родитель", "Parent/Guardian"),
    ("external_api", "Tashqi API", "Внешний API", "External API consumer"),
]

# UI navigation: minimum permission to show menu item
NAV_PERMISSIONS: dict[str, str] = {
    "dashboard": "dashboard.view",
    "centers": "centers.read",
    "students": "students.read",
    "teachers": "teachers.read",
    "groups": "groups.read",
    "attendance": "attendance.read",
    "payments": "payments.read",
    "ratings": "ratings.view",
    "certificates": "students.read",
    "analytics": "analytics.view",
    "security": "dashboard.view",
}
