"""Extended permissions for OCMS platform (8+ roles)."""

MANDATORY_MFA_ROLES = {"super_admin", "hokimiyat_operator", "center_director"}

_EXAM_PERMS = ["exams.create", "exams.read", "exams.update", "exams.delete", "exams.submit"]
_GRADE_PERMS = ["grades.create", "grades.read", "grades.update", "grades.delete"]
_COURSE_PERMS = ["courses.create", "courses.read", "courses.update", "courses.delete"]

_MESSAGE_PERMS = ["messages.read", "messages.send"]

ROLE_PERMISSIONS: dict[str, list[str]] = {
    "super_admin": [
        "centers.create",
        "centers.read",
        "centers.update",
        "centers.delete",
        "students.create",
        "students.read",
        "students.update",
        "students.delete",
        "teachers.create",
        "teachers.read",
        "teachers.update",
        "teachers.delete",
        "groups.create",
        "groups.read",
        "groups.update",
        "groups.delete",
        "groups.enroll",
        "attendance.read",
        "attendance.mark",
        "payments.read",
        "payments.create",
        "payments.update",
        "ratings.view",
        "reports.generate",
        "system.settings",
        "users.password_reset",
        "security.credentials.issue",
        "pinfl.reveal",
        "audit.read",
        "dashboard.view",
        "analytics.view",
        *_EXAM_PERMS,
        *_GRADE_PERMS,
        *_COURSE_PERMS,
        "files.upload",
        "files.read",
        *_MESSAGE_PERMS,
    ],
    "hokimiyat_operator": [
        "centers.create",
        "centers.read",
        "students.read",
        "teachers.read",
        "groups.read",
        "attendance.read",
        "ratings.view",
        "reports.generate",
        "audit.read",
        "dashboard.view",
        "analytics.view",
        "exams.read",
        "grades.read",
        "courses.read",
    ],
    "center_director": [
        "centers.read",
        "centers.update",
        "students.create",
        "students.read",
        "students.update",
        "students.delete",
        "teachers.create",
        "teachers.read",
        "teachers.update",
        "groups.create",
        "groups.read",
        "groups.update",
        "groups.delete",
        "groups.enroll",
        "attendance.read",
        "attendance.mark",
        "payments.read",
        "payments.create",
        "payments.update",
        "ratings.view",
        "reports.generate",
        "users.password_reset",
        "security.credentials.issue",
        "dashboard.view",
        "analytics.view",
        *_EXAM_PERMS,
        *_GRADE_PERMS,
        *_COURSE_PERMS,
        "files.upload",
        "files.read",
        *_MESSAGE_PERMS,
    ],
    "center_admin": [
        "centers.read",
        "students.create",
        "students.read",
        "students.update",
        "teachers.read",
        "groups.create",
        "groups.read",
        "groups.update",
        "groups.enroll",
        "attendance.read",
        "attendance.mark",
        "payments.read",
        "payments.create",
        "ratings.view",
        "dashboard.view",
        "exams.read",
        "exams.create",
        "grades.read",
        "grades.create",
        "courses.read",
        "files.upload",
        "files.read",
    ],
    "teacher": [
        "teacher.portal",
        "students.read",
        "groups.read",
        "attendance.read",
        "attendance.mark",
        "exams.read",
        "exams.create",
        "grades.read",
        "grades.create",
        "courses.read",
        "messages.read",
        "messages.send",
    ],
    "accountant": [
        "students.read",
        "payments.read",
        "payments.create",
        "payments.update",
        "reports.generate",
        "dashboard.view",
    ],
    "auditor": [
        "centers.read",
        "students.read",
        "teachers.read",
        "groups.read",
        "attendance.read",
        "ratings.view",
        "reports.generate",
        "audit.read",
        "dashboard.view",
        "analytics.view",
        "exams.read",
        "grades.read",
    ],
    "student": [
        "students.read",
        "grades.read",
        "attendance.read",
        "exams.read",
        "exams.submit",
        "certificates.read",
    ],
    "parent": [
        "students.read",
        "ratings.view",
        "certificates.read",
        "grades.read",
        "attendance.read",
    ],
    "external_api": [
        "aggregate_stats.read",
    ],
}

ROLE_DEFINITIONS = [
    ("super_admin", "Super administrator", "Super administrator", "Super administrator"),
    ("hokimiyat_operator", "Operator", "Оператор", "Operator"),
    ("center_director", "Direktor", "Директор", "Director"),
    ("center_admin", "Menejer", "Менеджер", "Manager"),
    ("teacher", "O'qituvchi", "Учитель", "Teacher"),
    ("accountant", "Buxgalter", "Бухгалтер", "Accountant"),
    ("student", "O'quvchi", "Учащийся", "Student"),
    ("auditor", "Auditor", "Аудитор", "Auditor"),
    ("parent", "Ota-ona", "Родитель", "Parent/Guardian"),
    ("external_api", "Tashqi API", "Внешний API", "External API consumer"),
]

NAV_PERMISSIONS: dict[str, str] = {
    "dashboard": "dashboard.view",
    "centers": "centers.read",
    "students": "students.read",
    "teachers": "teachers.read",
    "groups": "groups.read",
    "courses": "courses.read",
    "attendance": "attendance.read",
    "payments": "payments.read",
    "exams": "exams.read",
    "grades": "grades.read",
    "ratings": "ratings.view",
    "certificates": "ratings.view",
    "analytics": "analytics.view",
    "security": "users.password_reset",
    "messages": "messages.read",
}
